spring:
  application:
    name: backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:7080/realms/sentinel-nexus-realm
          # The jwk-set-uri property points to the URI containing the public key so that our Resource Server can verify the tokens’ integrity
          jwk-set-uri: http://host.docker.internal:7080/realms/sentinel-nexus-realm/protocol/openid-connect/certs

server:
  port: 9999
